### ISSUE TITLE
Black screen when calling

### ISSUE THREAD

**Issue by andreiciocanvlad** [JDCTeam/issue_tracking_cm13#2]
When initiating a call the screen becomes black as if proximity is on. Only turns on after call ends

**Comment by dkati** [comment]
try recalibrate ur sensor :)

**Comment by andreiciocanvlad** [comment]
How ? I had same problem with cm12

**Comment by dkati** [comment]
http://forum.xda-developers.com/showthread.php?t=2569141

**Comment by andreiciocanvlad** [comment]
Can't get into _#0_# in dial

**Comment by dkati** [comment]
Follow these steps
1. download Android Terminal from store
2. type these commands to calibrate automatically
$ su

# echo 0 > /sys/devices/virtual/sensors/proximity_sensor/prox_cal

# echo 1 > /sys/devices/virtual/sensors/proximity_sensor/prox_cal

u only need this

**Comment by andreiciocanvlad** [comment]
Ok thx i'll get back

**Comment by andreiciocanvlad** [comment]
It did fix it over Adb. This should be mentioned somewhere easy to read. Thx

**Comment by smeroni68** [comment]
It's an hardware issue (proximity sensor has dust over it and the reading is falsed). My personal suggestion is to open the phone (quite easy and well detailed on youtube) and remove definitively the dust... but it's needed a bit of skill to take this way.
The solution given is one of the available around (google it or search on xda threads, is full of methods well explained).
If is not a rom issue, why mention it in our thread? Thanks to @dkati that has helped you, but due to the fact that you had the same problem also on CM12, probably it's not correct to use this channel to search help.

Sorry.
